pipelines:
  yamlpipe2:
    group: test
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/saifally/gradle-simple.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: ls
